# General
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Bluetooth
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Encoders (EC11)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y

# Keyboard behavior
CONFIG_ZMK_KEYBOARD_NAME="KT55"

